services:
  - type: web
    name: detector-de-ia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app_streamlit.py --server.port=$PORT --server.address=0.0.0.0
    plan: free
